name: CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-practice .

      - name: Push the image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-practice