name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: axelpsql
          POSTGRES_DB: springpractice
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 && break
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Initialize database schema
        env:
          PGPASSWORD: axelpsql
        run: |
          psql -h localhost -U postgres -d springpractice -c "CREATE TABLE IF NOT EXISTS test_table(id SERIAL PRIMARY KEY, name VARCHAR(255));"
          # Ajoute ici d'autres scripts SQL si besoin, par exemple via un fichier SQL
          # psql -h localhost -U postgres -d springpractice -f path/to/init.sql

      - name: Build and test with Maven
        run: mvn clean test
